### ISSUE TITLE
Notice of Copyright/License Violation

### ISSUE THREAD

**Issue by Fuzzbawls** [Crave-Project/Crave-NG#1]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license has been modified to explicitely exclude the PIVX developers.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository.

**Comment by CooleRRSA** [comment]
Sorry for missed copyright. Fixed.
https://github.com/Crave-Project/Crave-NG/commit/74d47031e2b218f82eaa6a8ba6106e255f7aff0c

**Comment by Fuzzbawls** [comment]
Thank you :)
