### ISSUE TITLE
getblocktemplate memory error

### ISSUE THREAD

**Issue by coolindark** [Crave-Project/Crave-NG#4]
Hello. getblocktemplate returns with "out of memory" error in linux and the same command halts the Windows wallet also. I've also compiled 2 previous sources but all gives the same errors. Any trick to bypass this?

Thanks.

**Comment by coolindark** [comment]
Means POW is over for Crave?

**Comment by CooleRRSA** [comment]
Yes. New Crave blockchain has PoW phase only for making premine for coinswap. It's only PoS coin now.
