### ISSUE TITLE
Asking myself if ...

### ISSUE THREAD

**Issue by jagottsicher** [Crave-Project/Crave-NG#6]
... Asking myself if Crave has a chance to develop support for the Lightning Network. The better question is if there stands anything against a support for the Lightning Network.

Background:
I see a big chance that the Lightning Network will wipe out lots of security, anonymity and safety-based cryptos, except they have the potential to join the lighting network and take part at atomic swaps within the the LN. 

So this Question is mainly addressed to @CooleRRSA

**Comment by jagottsicher** [comment]
nobody?

**Comment by CooleRRSA** [comment]
Hello.
Crave do not have problems with transactions bandwidth. 60 seconds blocks  
and larger blocksize.
So Lighting Network support is not needed at this point of time.

jagottsicher <notifications@github.com> писал(а) в своём письме Sun, 09  
Sep 2018 15:45:33 +0300:

**Comment by jagottsicher** [comment]
Thanks for the answer, but the question is not, if it is needed, but if it possible. 

Other altcoins will never be able to join the lightning network, because the don't support Segwit for example. I know there is no specific plan to integrate crave, but was there any technical reason which makes it impossible in the future?

**Comment by CooleRRSA** [comment]
There is no any technicals limitation for integrating this features.
The main problem is that Segwit or Lightning Network intergration requires  
hardfork
with mandatory wallet upgrade. And it's very painful procedure for  
masternode holders.

jagottsicher <notifications@github.com> писал(а) в своём письме Thu, 13  
Sep 2018 15:40:36 +0300:

**Comment by jagottsicher** [comment]
Thanks again!

I run three crave masternodes on my own and know that it would be some kind of "kick-in-the-ass". 

Anyway thanks for enlightment!
